successfully changed the Level-1/code.yml
skills/secure-code-game pull request #69
Opened 2024-01-21 18:44 UTC by Debshibraj123

### Summary

### Changes

Closes:

### Task list

- [ ] For workflow changes, I have verified the Actions workflows function as expected.
- [ ] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

2024-01-21 23:59 UTC, jkcso commented
@dduzgun-security What do you think?

2024-01-22 07:00 UTC, dduzgun-security requested changes
I think it would be good if we keep the `permissions` section since it restricts the default `GITHUB_TOKEN` [permission](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) used in the GitHub Action to only `contents: read`.

2024-01-22 07:19 UTC, dduzgun-security reviewed
Good idea to remove the `Check out code` step here. It would be nice to mention it as an item below in the **Solution Explanation**. Maybe something like: `# 7. Think about removing unnecessary steps in the GitHub Actions.`

> [!NOTE]  
> In this example the checkout step _copies_ the code in a GitHub runner but we actually don't need that step to run a simple `curl`. Removing it reduces the code of being _copied_ (gain in time) and therefore reduces the potential risk of code exposure if an attacker has access to the runner or finds a way to exploit the actions/checkout GitHub Action (gain in security).

2024-01-22 09:10 UTC, jkcso commented
Thank you @dduzgun-security, feel free to suggest code + solution additions in the PR, make sure that you test too and I will review at the end to accept :-) Thanks!

2024-02-01 18:14 UTC, dduzgun-security commented
👋 Hey @Debshibraj123, what do you think about the requested changes? I would have loved to suggest code change but it doesn't allow on removed lines of code.

2024-03-25 22:08 UTC, jkcso commented
@Debshibraj123 any updates here please?

2024-04-06 12:51 UTC, nxhettry commented
Guys i am a beginner, this suddenly appeared in my pull request. What is this? Someone tell me.

2024-04-06 12:52 UTC, nxhettry commented
What are these comments and commits related to?

2024-04-07 21:25 UTC, jkcso commented
@nxhettry don't worry my friend, nothing to do here for you

2024-04-07 23:22 UTC, dduzgun-security commented on Season-2/Level-1/solution.yml
>      runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-latest
    permissions:
      contents: read
```

2024-04-07 23:25 UTC, dduzgun-security commented
@jkcso If that sounds good with you, let's merge this and I'll address the [comment](https://github.com/skills/secure-code-game/pull/69#discussion_r1555106579) in another PR

2024-04-08 16:21 UTC, jkcso approved these changes

2024-04-08 16:23 UTC, merged